id: P000283
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 2021-12-16 15:10:53.558544
source_metadata:
  id: bdr:W1KG10241
  title: འཇུ་མི་ཕམ་གྱི་གསུང་འབུམ་ལས་དུས་འཁོར་གྱི་སྐོར།༼པོད་ཨེ་- ཝཾ།༽
  author: ''
  volumes:
    5fa191d2908649b5b5e9367d37d1195e:
      image_group_id: I1KG10243
      title: Volume 1 of dus 'khor sgrub thabs snying po rab gsal sogs/
      volume_number: 1
      total_pages: 1146
      base_file: v001.txt
    25077672a2b04f72ae0d248fecc666b0:
      image_group_id: I1KG10244
      title: Volume 2 of dus 'khor sgrub thabs snying po rab gsal sogs/
      volume_number: 2
      total_pages: 996
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
