id: I3BFB3507
legacy_id: P000283
ocr_import_info:
  bdrc_scan_id: W1KG10241
  source: bdrc
  ocr_info:
    timestamp: '2020-02-21T11:26:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T02:26:38.828370+00:00'
last_modified: 2022-08-31 10:29:23.603038
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10241
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10241
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇུ་མི་ཕམ་གྱི་གསུང་འབུམ་ལས་དུས་འཁོར་གྱི་སྐོར།༼པོད་ཨེ་- ཝཾ།༽
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.8002908882145712
  ocr_word_median_confidence_index: 0.8700000047683716
quality: null
bases:
  I1KG10244:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10244
      total_pages: 996
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG10244.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8552827847409856
    legacy_id: v002
  I1KG10243:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10243
      total_pages: 1146
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10243.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7585764282801586
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
